require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

# MapBox
$RNMBGL_Use_SPM = { # MapLibre, set to true if no version specified
  url: "https://github.com/maplibre/maplibre-gl-native-distribution",
  requirement: {
      kind: "exactVersion",
      version: "5.11.0"
  },
  product_name: "Mapbox"
}
pre_install do |installer|
  $RNMBGL.pre_install(installer)
end

target 'AccessMap' do
  permissions_path = '../node_modules/react-native-permissions/ios'

  # Pods for AccessMap
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  pod 'RNPostHog', :path => '../node_modules/posthog-react-native'

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  target 'AccessMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AccessMap-tvOS' do
  target 'AccessMap-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Mapbox post install
post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)

  $RNMBGL.post_install(installer)
end
